name: action_test

on:
  workflow_dispatch:

jobs:
  run_test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: call and execute action
        id: parser
        uses: WolfGear-Tech/Action-ParsePR@v1
        with:
          PR_TITTLE: 'v1.0.0'

      - name: print the output
        run: echo ${{ steps.parser.outputs.SEMVER_TAG }}
